replicaCount: 1
image:
  repository: patrick
  pullPolicy: IfNotPresent
  tag: "1.0.0"
containerPort: 8000
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
env: []

envFrom:
  - secretRef:
      name: patrick-gitlab-oauth

gitlab:
  clientId: ""
  clientSecret: ""
  redirectUri: "http://127.0.0.1:8000/api/auth/gitlab/callback"
  sessionSecret: ""
